name: Workflow Triggered by Other Repository to compile code

on:
  repository_dispatch:
    types: [compile-code]

jobs:
  compile-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run compile code
        run: echo "Performing compile code tasks..."
      - name: Complete task
        run: echo "code compiled tasks completed."
  build-image:
    needs: compile-code
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Set up Docker Buildx (for cross-platform build capabilities, if needed)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Ensure Docker is installed
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io

    # Log in to Docker Hub (replace DOCKER_USERNAME and DOCKER_PASSWORD with your secrets)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the Docker image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/testing-github:latest
