name: Workflow Triggered by Other Repository to compile code

on:
  repository_dispatch:
    types: [compile-code]

jobs:
  compile-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run compile code
        run: echo "Performing compile code tasks..."
      - name: Complete task
        run: echo "code compiled tasks completed."
  build-image:
    needs: compile-code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run build image
        run: echo "Performing buld image tasks..."
      - name: Complete Task
        run: echo "Build image tasks completed."
