name: Trigger Another Repository Workflow with Custom Payload

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      # First, check out the current repository to access the Git history
      - name: Check out the repository
        uses: actions/checkout@v2

      # Define the username, repository URL, and commit message
      - name: Trigger workflow in RepoA
        run: |
          USERNAME="${{ github.actor }}"  # Username of the action triggerer
          REPO_URL="https://github.com/${{ github.repository }}"  # Repository URL
          COMMIT_MESSAGE="$(git log -1 --pretty=%B)"  # Retrieve the latest commit message

          # Use the GitHub REST API to trigger a dispatch event in RepoA
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${TOKEN}" \
            https://api.github.com/repos/umasad087/RepoA/dispatches \
            -d "{\"event_type\": \"main-workflow-initiate\", \"client_payload\": {\"username\": \"$USERNAME\", \"repo_url\": \"$REPO_URL\", \"commit_message\": \"$COMMIT_MESSAGE\"}}"
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
