name: Trigger Workflow in Another Repository with Custom Payload

on:
  push:
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: main workflow initate
        run: |
          
          USERNAME="${{ github.actor }}"
          REPO_URL="https://github.com/${{ github.repository }}"
          COMMIT_MESSAGE="$(git log -1 --pretty=%B)"
          
          
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${TOKEN}" \
            https://api.github.com/repos/umasad087/ReopA/dispatches \
            -d "{\"event_type\": \"main-workflow-initiate\", \"client_payload\": {\"username\": \"$USERNAME\", \"repo_url\": \"$REPO_URL\", \"commit_message\": \"$COMMIT_MESSAGE\"}}"
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
