name: Workflow Triggered by Other Repository

on:
  repository_dispatch:
    types: [triggered-from-other-repo]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run tasks
        run: echo "Performing tasks..."
      - name: Complete task
        run: echo "Tasks completed."
